### ISSUE TITLE
The server can handle how many concurrent clients?

### ISSUE THREAD

**Issue by mokhtarabadi** [novnc/websockify-other#13]
I mean c

**Comment by CendioOssman** [comment]
There is no limit in the code so it will handle as many connections as your hardware has resources for.

**Comment by mokhtarabadi** [comment]
Hi @CendioOssman,
is there something like https://github.com/MisakaMikoto-35c5/websockify-client in c?
mean websockify client in c

**Comment by CendioOssman** [comment]
I'm afraid I'm not aware of any client written in C, no.

**Comment by mokhtarabadi** [comment]
websocksify is a great project, this can used as a tunnel to forward ports behind the firewall if there is a client available!
i'm java developer and writing the java client for android but in android the native network (which was written in c/c++) is very faster than java network
did you have any plan to make this available?
