### ISSUE TITLE
Feature request: Simple web server support in C version.

### ISSUE THREAD

**Issue by twaik** [novnc/websockify-other#14]
Hi. I noticed that C version websockify is missing simple web server feature. Can you please add it? I tried to do that, but it was a very ugly solution.

**Comment by CendioOssman** [comment]
No is really working on this code, but if someone wants to give it a go we can see if it can be merged.

**Comment by osen** [comment]
Hello. I have recently finished my WebSocket proxy (WsStent) here:

https://www.thamessoftware.co.uk/forge?repo=wsstent

Some features it has are:

- Written entirely in C (c89)
- Uses non-blocking sockets (can work on admittedly rare platforms with no multi-threading)
- Very memory safe in that it uses a fairly elaborate tombstone system (libstent)
- Provides a simple www server (like websockify)
- Enforces SSL in websocket end but unencrypted sockets on the TCP endpoint.

I have only just recently tested it with noVNC and it seems to work well. BSD-2-clause licensed. Happy for people to use it.

**Comment by twaik** [comment]
Stale issue.
