### ISSUE TITLE
Websockify-c: Sec-WebSocket-Origin is mandatory not following RFC3864

### ISSUE THREAD

**Issue by clementperon** [novnc/websockify-other#16]
Hi,

In the C parser the "Sec-WebSocket-Origin: " seems mandatory whereas the RFC3864 says: 

The request MUST include a header with the name "Sec-WebSocket-Origin" if the request is coming from a browser client. If the connection is from a non-browser client, the request **MAY** include this header if the semantics of that client match the use-case described here for browser clients. The value of this header MUST be the ASCII serialization of origin of the context in which the code establishing the connection is running, and MUST be lower-case. The value MUST NOT contain letters in the range U+0041 to U+005A (i.e. LATIN CAPITAL LETTER A to LATIN CAPITAL LETTER Z) [I-D.ietf-websec-origin].

**Comment by clementperon** [comment]
@CendioOssman

**Comment by CendioOssman** [comment]
That RFC number seems incorrect? RFC 6455 is the one for WebSocket. And it does not include that header, even though it was included in the drafts. So that handling should be removed as it is not a standard header. And that's what happen in #15, so I'll go ahead and close this issue.
