### ISSUE TITLE
websockify stucks at select timeout

### ISSUE THREAD

**Issue by avp24** [novnc/websockify-other#19]
Hi,
I am using websockify to transfer Encoded Video Streams (H.264) captured from RTSP server to a player integrated in WeB-UI.
The behavior observed is randomly websockify stops passing the stream as it gets stuck in "select timeout" in **void do_proxy(ws_ctx_t *ws_ctx, int target)** in websockify.c
The socket connection state remains in ESTABLISHED mode though no packets are forwarded from websockify.
The arguments passed to execute websockify are: /customer/websockify --cert /customer/libs/lighttpd/ssl/server.crt --key /customer/libs/lighttpd/ssl/server.key 9500 192.168.1.250:554 &

**Comment by gstrauss** [comment]
FYI: [lighttpd mod_wstunnel](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModWSTunnel) might be an alternative to websockify

lighttpd doc has an example how to use noVNC to connect to a VNC server through lighttpd mod_wstunnel:
https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModWSTunnel#Example-websocket-tunnel-to-VNC-server-via-noVNC-client

**Comment by avp24** [comment]
@samhed We cannot use python version due to memory limitations.

**Comment by samhed** [comment]
Thanks @gstrauss for the tip, I'll try it out someday.

@avp24 ok, I understand. For troubleshooting purposes it would be helpful however to see in what end the issue might be. I'm a bit hard pressed on time here, would it be possible for you to test both the C variant and the Python variant on a different machine where you don't have memory constraints? Try to use a similar setup to the original scenario.

**Comment by avp24** [comment]
Hi @samhed 
To generate original scenario using python wont be possible on different machine and due to memory constraints cannot use python libraries. Can you please help with C variant?

**Comment by avp24** [comment]
Hi @samhed 
Sorry for responding late as this issue priority went into background.
Apart from select time out error which I reported I also get these error prints in websockify "!!!! client sent orderly close frame !!!!" when connected with browser (Chrome,Mozilla) and then my video stream stops on browser.
Also if creating multiple websockify sessions by connecting with multiple browser (approx 3 or more tabs) then also video stream stucks at browser as the packets are forwarded from websockify to browser. In this case to support multiple sessions is any modification in websockify or network stack required?
Please share your inputs.

Thanks.

**Comment by samhed** [comment]
Talking about additional issues isn't helpful at this stage when we can't even reproduce the original issue. Let's focus on one thing at a time - as I asked in my previous response, is there anything special I can try that you think will trigger this select timeout freeze?

**Comment by avp24** [comment]
No there is nothing special required to generate the issue. Maybe can you try to connect multiple clients (Browser) to your websockify and transfer the data. 
The issues which I shared were observed with such cases even the "select timeout" case as well.
You are executing websockify on x86 or some different architecture?

**Comment by avp24** [comment]
@samhed Did you face issue in case of multiple clients?

**Comment by samhed** [comment]
Hi again @avp24 sorry for the late response.

I have now tested with 5 clients connected at the same time, they have been connected without issue for 1 hour now. It seems I still can't reproduce the problem, unfortunately.

**Comment by avp24** [comment]
Hi @samhed 
After upgrading my RTSP server to latest version I am not observing this issue. I checked with 8 clients connected at same time. 
Closing this issue.
Thank you for your help.
